# Generated by Django 5.0.2 on 2024-03-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_subtasks_subtask_id_alter_user_task_list_l_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_subtask_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todos.subtasks'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notif_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
